name: Build TS SDK
on:
  push:
    tags:
      - 'ts*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.3
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run workflow:check && pnpm run build